const Router = require("@koa/router");
const router = new Router();
const shopinfoRouter = require("./shopinfo.routes");
const adsmanagment = require("./adsmanagment.routes");
const bikecategory = require("./bikecategory.routes");
const bikeinfo = require("./bikeinfo.routes");
const client = require("./client.routes");
const payment = require("./payment.routes");
const penalty = require("./penalty.routes");
const rental = require("./rental.routes");
const user = require("./user.routes");
const usergroup = require("./usergroup.routes");
const otp = require("./otp.routes");
const response = require("./responses.routes");
const { getTokens } = require("../controllers/token.controller");

router.use(response);
router.use("/api/otp", otp());
router.use("/api/shopinfo", shopinfoRouter());
router.use("/api/adsmanagment", adsmanagment());
router.use("/api/bikecategory", bikecategory());
router.use("/api/bikeinfo", bikeinfo());
router.use("/api/client", client());
router.use("/api/payment", payment());
router.use("/api/penalty", penalty());
router.use("/api/rental", rental());
router.use("/api/user", user());
router.use("/api/usergroup", usergroup());
router.get("/api/tokens", getTokens);
module.exports = router;
